"""initial schema + append-only audit log trigger (PostgreSQL)

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 22:35:01.646540
"""

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=254), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pseudonym_code', sa.String(length=64), nullable=False),
    sa.Column('hospital', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital', 'pseudonym_code', name='uq_patient_code')
    )
    op.create_index(op.f('ix_patients_hospital'), 'patients', ['hospital'], unique=False)
    op.create_index(op.f('ix_patients_pseudonym_code'), 'patients', ['pseudonym_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pathologist', 'urologist', name='role'), nullable=False),
    sa.Column('hospital', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret_enc', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hospital'), 'users', ['hospital'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('hospital', sa.String(length=120), nullable=False),
    sa.Column('slide_file', sa.String(length=255), nullable=False),
    sa.Column('slide_sha256', sa.String(length=64), nullable=False),
    sa.Column('slide_bytes', sa.BigInteger(), nullable=False),
    sa.Column('slide_format', sa.String(length=8), nullable=False),
    sa.Column('slide_seed_id', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'queued', 'processing', 'done', 'failed', name='case_status'), nullable=False),
    sa.Column('progress_stage', sa.String(length=40), nullable=True),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_deleted_at'), 'cases', ['deleted_at'], unique=False)
    op.create_index('ix_cases_hospital_status', 'cases', ['hospital', 'status'], unique=False)
    op.create_index(op.f('ix_cases_patient_id'), 'cases', ['patient_id'], unique=False)
    op.create_index('ix_cases_sha', 'cases', ['hospital', 'slide_sha256'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_jti', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=40), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_refresh_jti'), 'sessions', ['refresh_jti'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('suffix', sa.String(length=8), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('received_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('preprocessing_version', sa.String(length=200), nullable=False),
    sa.Column('p_cancer', sa.Float(), nullable=False),
    sa.Column('p_cspca', sa.Float(), nullable=False),
    sa.Column('p_isup', sa.JSON(), nullable=False),
    sa.Column('isup_grade', sa.Integer(), nullable=False),
    sa.Column('gleason_hint', sa.String(length=40), nullable=False),
    sa.Column('operating_point_flags', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('n_tiles', sa.Integer(), nullable=False),
    sa.Column('n_tiles_total', sa.Integer(), nullable=False),
    sa.Column('seed_std_p_cspca', sa.Float(), nullable=False),
    sa.Column('low_confidence_reasons', sa.JSON(), nullable=False),
    sa.Column('qc', sa.JSON(), nullable=False),
    sa.Column('slide_width', sa.Integer(), nullable=False),
    sa.Column('slide_height', sa.Integer(), nullable=False),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('device', sa.String(length=20), nullable=False),
    sa.Column('result_path', sa.String(length=255), nullable=False),
    sa.Column('heatmap_path', sa.String(length=255), nullable=False),
    sa.Column('top_tiles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_case_id'), 'predictions', ['case_id'], unique=False)
    op.create_index(op.f('ix_predictions_isup_grade'), 'predictions', ['isup_grade'], unique=False)
    op.create_index(op.f('ix_predictions_model_version'), 'predictions', ['model_version'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.Enum('confirmed', 'amended', 'rejected', name='decision'), nullable=False),
    sa.Column('final_isup', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_case_id'), 'reviews', ['case_id'], unique=False)
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # the audit trail is append-only: block UPDATE, DELETE and TRUNCATE at the database level
        op.execute("""
            CREATE FUNCTION audit_log_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'audit_log is append-only (% blocked)', TG_OP;
            END $$;
        """)
        op.execute("""CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log
                      FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();""")
        op.execute("""CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log
                      FOR EACH STATEMENT EXECUTE FUNCTION audit_log_append_only();""")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_case_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_predictions_model_version'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_isup_grade'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_case_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_jti'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_cases_sha', table_name='cases')
    op.drop_index(op.f('ix_cases_patient_id'), table_name='cases')
    op.drop_index('ix_cases_hospital_status', table_name='cases')
    op.drop_index(op.f('ix_cases_deleted_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_hospital'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_pseudonym_code'), table_name='patients')
    op.drop_index(op.f('ix_patients_hospital'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    for enum in ("decision", "case_status", "role"):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
